apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      containers:
        - name: vllm
          image: registry.redhat.io/rhaiis/vllm-cuda-rhel9:3.0.0
          command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
          args: ["--model", "mistralai/Mistral-7B-Instruct-v0.2", "--trust-remote-code"]
          ports:
            - containerPort: 8000
          env:
            - name: VLLM_PORT
              value: "8000"  # explicitly set to correct int value
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-secret
                  key: HUGGING_FACE_HUB_TOKEN
            - name: HF_HUB_OFFLINE
              value: "0"
            - name: VLLM_NO_USAGE_STATS
              value: "1"
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: redhat-pull-secret
